### ISSUE TITLE
No declaration type error

### ISSUE THREAD

**Issue by ashrafbaker** [nawforce/apex-assist#10]
Hi,
I'm using the VSCode plugin of Apex Assist, it seems to mention every single time the "No type declaration found for .."
and every-time it is for an object or a metadata type that is not recognised while it does exist, for example : 
List<MFieldMap__mdt> lstFields = MFieldMap__mdt.getAll().values();
The MFieldMap__mdt exists in the org.
I did an sobject refresh from VSCode and I didn't see any configuration to your plugin.
Can you let me know if I'm missing something?
Or is it really an issue on your side?
Thanks

**Comment by nawforce** [comment]
Hi Ashraf,

The problem here is that we expect all metadata to be in your workspace, we don't download metadata from the org so you will get an error. We have thought about using the metadata the Salesforce extensions download but there are a couple of problems with that, we need access to more than just SObjects and Salesforce themselves say we should not rely on the files they create in the .sfdx directory.

I am planning to look at this problem again and come up with a way to download the missing metadata from the org, but it likely that will not be available for a few months. There is an existing bug for this over at https://github.com/nawforce/apex-link/issues/40.

**Comment by ashrafbaker** [comment]
Thanks for the follow up, I appreciate it, and your work.

**Comment by nawforce** [comment]
No problem, the good news is the additional tooling I was referring to is written. I just need to do some more testing on it and and make some adjustments to the extension to use the downloaded metadata and we should have a solution to this.

**Comment by nawforce** [comment]
You can now download metadata from an org, little demo video at [youtu.be/B4lznOZ7Wts](https://t.co/PnI9NvkPcQ).
